// <auto-generated />
using System;
using CarBMW.API.MODEL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarBMW.API.Migrations
{
    [DbContext(typeof(Dbcontext))]
    partial class DbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarBMW.API.MODEL.AllotInfo", b =>
                {
                    b.Property<int>("Awid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ALeaveTimes")
                        .HasColumnType("int");

                    b.Property<int>("ASignTimes")
                        .HasColumnType("int");

                    b.Property<int>("AWithdrawalTimes")
                        .HasColumnType("int");

                    b.Property<string>("Acategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Departmentid")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeMessageid")
                        .HasColumnType("int");

                    b.HasKey("Awid");

                    b.ToTable("AllotInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.Attendance", b =>
                {
                    b.Property<int>("Acwaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ALeaveTimes")
                        .HasColumnType("int");

                    b.Property<int>("ASignTimes")
                        .HasColumnType("int");

                    b.Property<int>("AWithdrawalTimes")
                        .HasColumnType("int");

                    b.Property<string>("Acategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Departmentid")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeMessageid")
                        .HasColumnType("int");

                    b.HasKey("Acwaid");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.Attribute", b =>
                {
                    b.Property<int>("Caid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atid")
                        .HasColumnType("int");

                    b.Property<int>("Commodityid")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Caid");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.CarMessage", b =>
                {
                    b.Property<int>("Iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COlour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CWarehouseTypeid")
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<int>("Clientid")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Iid");

                    b.ToTable("CarMessage");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.CarSet", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Series")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cid");

                    b.ToTable("CarSet");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.ClientMessage", b =>
                {
                    b.Property<int>("Clientid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientSex")
                        .HasColumnType("int");

                    b.Property<int>("Clientphone")
                        .HasColumnType("int");

                    b.HasKey("Clientid");

                    b.ToTable("ClientMessage");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.ClientOrder", b =>
                {
                    b.Property<int>("COid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarMessageid")
                        .HasColumnType("int");

                    b.Property<int>("ClientMessageid")
                        .HasColumnType("int");

                    b.Property<float>("ClientPrice")
                        .HasColumnType("real");

                    b.Property<int>("OrderSale")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ordertime")
                        .HasColumnType("datetime2");

                    b.HasKey("COid");

                    b.ToTable("ClientOrder");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.Commodity", b =>
                {
                    b.Property<int>("Cmid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Cmid");

                    b.ToTable("Commodity");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.CompanyFinance", b =>
                {
                    b.Property<int>("CFid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Cfzprice")
                        .HasColumnType("real");

                    b.HasKey("CFid");

                    b.ToTable("CompanyFinance");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.DepartmentInfo", b =>
                {
                    b.Property<int>("DIid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DIid");

                    b.ToTable("DepartmentInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.EmployeeLeave", b =>
                {
                    b.Property<int>("ELid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ELEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ELStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeMessageid")
                        .HasColumnType("int");

                    b.Property<int>("LeaveStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReasonsLeave")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ELid");

                    b.ToTable("EmployeeLeave");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.EmployeeMessage", b =>
                {
                    b.Property<int>("Emid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Departmentid")
                        .HasColumnType("int");

                    b.Property<string>("EMAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Emage")
                        .HasColumnType("int");

                    b.Property<int>("Emphone")
                        .HasColumnType("int");

                    b.Property<bool>("Emsex")
                        .HasColumnType("bit");

                    b.HasKey("Emid");

                    b.ToTable("EmployeeMessage");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.EmployeeSalary", b =>
                {
                    b.Property<int>("Esid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientMessageid")
                        .HasColumnType("int");

                    b.Property<int>("ClientOrderid")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeMessageid")
                        .HasColumnType("int");

                    b.Property<int>("Wageid")
                        .HasColumnType("int");

                    b.HasKey("Esid");

                    b.ToTable("EmployeeSalary");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.InWarehouesInfo", b =>
                {
                    b.Property<int>("Iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CKid")
                        .HasColumnType("int");

                    b.Property<int>("CarMessageid")
                        .HasColumnType("int");

                    b.Property<int>("CarSetid")
                        .HasColumnType("int");

                    b.Property<int>("IISale")
                        .HasColumnType("int");

                    b.Property<int>("Iinum")
                        .HasColumnType("int");

                    b.Property<int>("InWarecode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Rktime")
                        .HasColumnType("datetime2");

                    b.HasKey("Iid");

                    b.ToTable("InWarehouesInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.MenuInfo", b =>
                {
                    b.Property<int>("Menuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Menuid");

                    b.ToTable("MenuInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.MyshoppingCar", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarConfigure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommodityPrice")
                        .HasColumnType("int");

                    b.Property<string>("MyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Sid");

                    b.ToTable("MyshoppingCar");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.OutWareInfo", b =>
                {
                    b.Property<int>("OIid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CKid")
                        .HasColumnType("int");

                    b.Property<DateTime>("CKtime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CWarehouesid")
                        .HasColumnType("int");

                    b.Property<int>("CarMessageid")
                        .HasColumnType("int");

                    b.Property<int>("CarSetid")
                        .HasColumnType("int");

                    b.Property<int>("Iinum")
                        .HasColumnType("int");

                    b.Property<int>("OISale")
                        .HasColumnType("int");

                    b.Property<string>("OIcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OIid");

                    b.ToTable("OutWareInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.Property", b =>
                {
                    b.Property<int>("Atid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttriBute")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Atid");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.Provinces", b =>
                {
                    b.Property<int>("Prid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sbid")
                        .HasColumnType("int");

                    b.HasKey("Prid");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.PurchaseDate", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarSetid")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("PurchasDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QualityTesting")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Wdid")
                        .HasColumnType("int");

                    b.HasKey("Pid");

                    b.ToTable("PurchaseDate");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.RoleInfo", b =>
                {
                    b.Property<int>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Roleid");

                    b.ToTable("RoleInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.RoleMenu", b =>
                {
                    b.Property<int>("Rmid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MenuInfoid")
                        .HasColumnType("int");

                    b.Property<int>("RMSale")
                        .HasColumnType("int");

                    b.Property<int>("Roleid")
                        .HasColumnType("int");

                    b.HasKey("Rmid");

                    b.ToTable("RoleMenu");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.SignOut", b =>
                {
                    b.Property<int>("SOEmtid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("SOCheckTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SOEmid")
                        .HasColumnType("int");

                    b.Property<int>("SOWithStatus")
                        .HasColumnType("int");

                    b.HasKey("SOEmtid");

                    b.ToTable("SignOut");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.Site", b =>
                {
                    b.Property<int>("Adid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SpecificAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Adid");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.StaffSign", b =>
                {
                    b.Property<int>("Sempid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SCheckStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("SCheckTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Semid")
                        .HasColumnType("int");

                    b.HasKey("Sempid");

                    b.ToTable("StaffSign");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.TimeInfo", b =>
                {
                    b.Property<int>("Timeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("QDtime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("QTtime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SBtime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("XBtime")
                        .HasColumnType("datetime2");

                    b.HasKey("Timeid");

                    b.ToTable("TimeInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.UserInfo", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserPwd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.UserRole", b =>
                {
                    b.Property<int>("Urid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleInfoid")
                        .HasColumnType("int");

                    b.Property<int>("UserInfoid")
                        .HasColumnType("int");

                    b.HasKey("Urid");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.Wage", b =>
                {
                    b.Property<int>("Wageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Emid")
                        .HasColumnType("int");

                    b.Property<float>("Wages")
                        .HasColumnType("real");

                    b.HasKey("Wageid");

                    b.ToTable("Wage");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.WarehouesDetailInfo", b =>
                {
                    b.Property<int>("Wdid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarMessageid")
                        .HasColumnType("int");

                    b.Property<int>("CarSetid")
                        .HasColumnType("int");

                    b.Property<int>("WDSale")
                        .HasColumnType("int");

                    b.Property<int>("WDnum")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseTypeInfoid")
                        .HasColumnType("int");

                    b.HasKey("Wdid");

                    b.ToTable("WarehouesDetailInfo");
                });

            modelBuilder.Entity("CarBMW.API.MODEL.WarehouesTypeInfo", b =>
                {
                    b.Property<int>("WTid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("WTName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WTSale")
                        .HasColumnType("int");

                    b.Property<int>("Wtcapacity")
                        .HasColumnType("int");

                    b.HasKey("WTid");

                    b.ToTable("WarehouesTypeInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
